### ISSUE TITLE
Timeout / CPU 100%

### ISSUE THREAD

**Issue by benoror** [parroty/exvcr#130]
I'm getting a timeout error exclusively when running ExVCR tests (EC2 t2.micro / 1 core / 1 GB RAM):

```
test index/2 responds with procedures without filter name less than 3 (NebulaApiWeb.ProcedureControllerTest)
     test/nebula_api_web/controllers/procedure_controller_test.exs:36
     ** (ExUnit.TimeoutError) test timed out after 60000ms. You can change the timeout:

       1. per test by setting "@tag timeout: x"
       2. per case by setting "@moduletag timeout: x"
       3. globally via "ExUnit.start(timeout: x)" configuration
       4. or set it to infinity per run by calling "mix test --trace"
          (useful when using IEx.pry)

     Timeouts are given as integers in milliseconds.

     code: use_cassette "helix_list_procedures_less_3" do
     stacktrace:
       (elixir) lib/task.ex:481: Task.await/2
       test/nebula_api_web/controllers/procedure_controller_test.exs:37: (test)
       (ex_unit) lib/ex_unit/runner.ex:306: ExUnit.Runner.exec_test/1
       (stdlib) timer.erl:166: :timer.tc/1
       (ex_unit) lib/ex_unit/runner.ex:245: anonymous fn/4 in ExUnit.Runner.spawn_test/3
```

**Comment by benoror** [comment]
Turns out it has to do with this README comment:

> TODO
> Improve performance, as it's very slow.
